version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/" # Location of your Dockerfile(s)
    schedule:
      interval: "daily" # How often to check for updates
      time: "17:00"
      timezone: "America/Los_Angeles"
